name: Build Kivy APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK with Buildozer
        uses: ArtemShtepenko/Buildozer-action@v1.2.0
        id: buildozer
        with:
          command: buildozer android debug
          subfolder: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: ${{ steps.buildozer.outputs.filename }}
